# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: live and code
email: wangkangfei@yeah.net
description:  I'm an android developer working in Beijing, China. I love open source and I'm making my best effort to learn android developing, 
                I hope to become a senior developer one day. If you have any questions, don't hesitate to contact me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: boomstack
github_username:  boomstack

# Build settings
markdown: kramdown

# theme: jekyll-theme-cayman
